name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e
            cd ~/portfolio-vps-deployment

            echo "Pulling latest code..."
            git pull

            echo "Check if frontend changed..."
            if git diff --name-only HEAD~1 HEAD | grep -q '^frontend/'; then
              echo "Frontend changed - building..."
              cd frontend
              npm install
              npm run build
              pm2 restart frontend
              cd ..
            else
              echo "No changes in frontend - skipping build."
            fi

            echo "Restart backend..."
            pm2 restart backend
          EOF
