name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # Inject .env into frontend for build
      - name: Create .env for frontend build
        run: |
          echo "${{ secrets.EC2_FRONTEND_ENV_FILE }}" > frontend/.env

      # Inject .env for backend
      - name: Create .env for backend deploy
        run: |
          echo "${{ secrets.EC2_BACKEND_ENV_FILE }}" > backend/.env

      # Build frontend on GitHub Actions (NOT on EC2!)
      - name: Build frontend
        run: |
          cd frontend
          npm ci
          npm run build

      # === DEPLOY FRONTEND ===

      # Clear old frontend build on EC2
      - name: Clear old frontend build (.next) on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "rm -rf ~/portfolio-vps-deployment/frontend/.next"

      # Rsync frontend source code to EC2
      - name: Rsync frontend source code to EC2
        run: |
          rsync -avz --delete \
            --exclude 'node_modules' \
            --exclude '.next' \
            -e "ssh -o StrictHostKeyChecking=no" \
            frontend/ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu/portfolio-vps-deployment/frontend/

      # Rsync frontend build (.next) to EC2
      - name: Rsync frontend build (.next) to EC2
        run: |
          rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no" \
            frontend/.next/ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu/portfolio-vps-deployment/frontend/.next

      # Rsync frontend .env to EC2
      - name: Rsync frontend .env to EC2
        run: |
          rsync -avz frontend/.env ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu/portfolio-vps-deployment/frontend/.env

      # === DEPLOY BACKEND ===

      # Rsync backend source code to EC2
      - name: Rsync backend source code to EC2
        run: |
          rsync -avz --delete \
            --exclude 'node_modules' \
            -e "ssh -o StrictHostKeyChecking=no" \
            backend/ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu/portfolio-vps-deployment/backend/

      # Rsync backend .env to EC2
      - name: Rsync backend .env to EC2
        run: |
          rsync -avz backend/.env ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu/portfolio-vps-deployment/backend/.env

      # === RESTART SERVICES ===

      # Restart services on EC2 with PM2 (safe restart)
      - name: Restart services on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -ex

            # Backend restart
            cd ~/portfolio-vps-deployment/backend
            echo ">>> Restarting backend"
            pm2 delete backend || true
            pm2 start npm --name backend -- start

            # Frontend restart
            cd ~/portfolio-vps-deployment/frontend
            echo ">>> Restarting frontend"
            pm2 delete frontend || true
            pm2 start npm --name frontend -- start
          EOF
