name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Build frontend
        run: |
          cd frontend
          npm ci
          npm run build

      - name: Rsync code to EC2
        run: |
          rsync -avz --exclude '.git' --exclude 'node_modules' --exclude 'frontend/node_modules' --exclude 'frontend/.next/cache' -e "ssh -o StrictHostKeyChecking=no" ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu/portfolio-vps-deployment

      - name: Restart services on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -ex
            cd ~/portfolio-vps-deployment/backend
            pm2 restart backend
            cd ../frontend
            pm2 restart frontend
          EOF
